### ISSUE TITLE
Maybe Server Side Error?

### ISSUE THREAD

**Issue by Onat125** [BrassAmber-Mods/soulbound-armory#14]
Hello, I opened a server for Excalibur's Crate, which is the modpack that includes this mod, but there is a problem that whenever we convert items to soulbonds, the game crashes. but there was no error on the server...
[crash-2023-01-22_16.09.36-client.txt](https://github.com/BrassAmber-Mods/soulbound-armory/files/10474569/crash-2023-01-22_16.09.36-client.txt)

**Comment by Onat125** [comment]
I forgot to mention this is a error for 1.19.2.

**Comment by nnym** [comment]
A probable fix is available in [version 3.3.0](https://www.curseforge.com/minecraft/mc-mods/soulbound-armory/files/4384857).
