### ISSUE TITLE
Multiplayer fix -urgent- 

### ISSUE THREAD

**Issue by BrassMcCrafty** [BrassAmber-Mods/soulbound-armory#15]
Players crash upon summoning a Soulbound item, either immediately or after 5-15 minutes **[observed time]**

Players can only re-join once inventory is wiped, but crash happens upon re-summon or after 5-15 minutes **[observed time]**

[crash-2023-01-29_12.50.55-client.txt](https://github.com/BrassAmber-Mods/soulbound-armory/files/10564660/crash-2023-01-29_12.50.55-client.txt)

**Comment by Onat125** [comment]
#14 this is the similar crash as we got, hopefully it will be fixed soon, we love the yagbox series...
