### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasia1403** [BrassAmber-Mods/soulbound-armory#18]
[crash-2023-02-07_10.12.22-server.txt](https://github.com/BrassAmber-Mods/soulbound-armory/files/10673414/crash-2023-02-07_10.12.22-server.txt)

**Comment by nnym** [comment]
Soulbound armory's development for Minecraft 1.12.2 has ceased ~2.75 years ago. I don't support this version of the mod any longer so I won't fix this issue.
