### ISSUE TITLE
About breaking blocks with a pickaxe in multiplayer...

### ISSUE THREAD

**Issue by Onat125** [BrassAmber-Mods/soulbound-armory#19]
Just one tap the game crashes when trying to break any block with pickaxe.  I don't know why... But I think it's related to soulbound armory.
[crash-2023-02-07_21.46.22-client.txt](https://github.com/BrassAmber-Mods/soulbound-armory/files/10678418/crash-2023-02-07_21.46.22-client.txt)

**Comment by nnym** [comment]
I can't reproduce this issue without other mods in singleplayer or multiplayer. I suggest trying without some or all of your other mods to see whether it's caused by any of them.

**Comment by Onat125** [comment]
> I can't reproduce this issue without other mods in singleplayer or multiplayer. I suggest trying without some or all of your other mods to see whether it's caused by any of them.



[crash-2023-02-09_13.32.55-client.txt](https://github.com/BrassAmber-Mods/soulbound-armory/files/10696121/crash-2023-02-09_13.32.55-client.txt)
We still encountered the same crash after a lot of trying, maybe the problem is from our world, I don't know, but I'll leave the crash report anyway, just jei and Soulbound armory installed.

**Comment by nnym** [comment]
I made a a new Forge 43.2.4 server, added soulbound armory 3.4.0 and ran the server. My client had JEI 11.5.2.1007 and soulbound armory 3.4.0. I connected to the server, broke 3 wood blocks, made a wooden pickaxe, broke a stone block, transformed the wooden pickaxe into a soulbound pickaxe and broke a stone block therewith and nothing strange happened. Did you try making a new world?

**Comment by nnym** [comment]
3.3.1 works too.

**Comment by Onat125** [comment]
> I made a a new Forge 43.2.4 server, added soulbound armory 3.4.0 and ran the server. My client had JEI 11.5.2.1007 and soulbound armory 3.4.0. I connected to the server, broke 3 wood blocks, made a wooden pickaxe, broke a stone block, transformed the wooden pickaxe into a soulbound pickaxe and broke a stone block therewith and nothing strange happened. Did you try making a new world?


We haven't created and tried a new world yet, but we'll try it , if we get any crashes, I'll continue to share.

**Comment by nnym** [comment]
Any news?
